#!/usr/bin/env python
from PIL import Image
import sys

def main():
	if (len(sys.argv) - 1) < 1:
		print "ERROR! Too few arguments ... type 'asciiGenerator -h' for help"
		return
	elif (len(sys.argv) - 1) > 1:
		print "ERROR! Too many arguments ... type 'asciiGenerator -h' for help"
		return
	elif sys.argv[1] == "-h":
		print "Usage: 'asciiGenerator [imageFileName]'"
		return
	else: 
		picture = sys.argv[1]
	
	try:
		image = Image.open(picture)
	except IOError:
		print "ERROR! Image not found"
		return
	
	picW , picH = image.size
	image = image.convert('LA')
	image = image.resize((100 , ((picH * 100) / picW)))
	
	asciiFile = open(picture + ".txt","w")
	
	makeAscii(image , asciiFile)
	

def makeAscii(pic, outputFile):
	for i in range(0, (pic.size)[1], 1):
		for j in range(0, (pic.size)[0], 1):
			pixelVal = (pic.getpixel((j,i)))[0] 
			if pixelVal < 51:
				outputFile.write("#".rstrip('\n'))
			elif pixelVal < 102 and pixelVal > 50:
				outputFile.write("%".rstrip('\n'))
			elif pixelVal < 153 and pixelVal > 101:
				outputFile.write(":".rstrip('\n'))
			elif pixelVal < 204 and pixelVal > 152: 
				outputFile.write(".".rstrip('\n'))
			elif pixelVal <= 255 and pixelVal > 203:
				outputFile.write(" ".rstrip('\n')) 
		outputFile.write('\n')
	outputFile.close
	return 

main()


	
